name: Deploy to S3 Public Bucket

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install AWS CLI (via pip)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync to S3 (Public Bucket)
        run: |
          aws s3 sync . s3://cs-demo-frontend \
            --delete \
            --acl public-read \
            --exclude ".git/*" \
            --exclude ".github/*"
